/**
 * Mission planning / decomposition (Architecture V2 · F1).
 *
 * The Executive Manager turns a Mission into structured Company Tasks. Planning is
 * SEPARATE from execution — it creates/updates tasks only, it never dispatches.
 * The LLM proposes a plan but the SERVER owns safety:
 *   - the raw plan is Zod-validated (MissionPlanSchema); an invalid plan fails safely
 *   - task ids are generated by the server, never trusted from LLM output
 *   - capability ids pass F0.1 validation (schema); dependencies pass F0.2 validation
 *   - apply is idempotent by title → a re-plan does not duplicate tasks
 * The LLM is injectable so the whole pipeline is testable without a live model.
 */
import type { FounderDb } from '@/lib/db';
import { chat as llmChat } from '@/lib/connectors/llm';
import { MissionPlanSchema, type MissionPlan } from '@/lib/company/manager/model';
import {
  CompanyError,
  addTaskDependency,
  createCompanyTask,
  getMission,
  listTasksForMission,
  updateMission,
} from '@/lib/company/service';
import { appendEvent } from '@/lib/company/manager/events';
import type { CompanyTask, Mission } from '@/lib/company/model';

const normTitle = (t: string): string => t.trim().toLowerCase();

/** Extract a JSON object from raw LLM text (fenced or bare) and validate it. Fails safely. */
export function parseMissionPlan(raw: string): MissionPlan {
  const fence = /```(?:json|plan)?\s*([\s\S]*?)```/i.exec(raw);
  const candidate = fence?.[1] ?? /\{[\s\S]*\}/.exec(raw)?.[0] ?? null;
  if (!candidate) throw new CompanyError('planner did not return a JSON plan', 400);
  let json: unknown;
  try {
    json = JSON.parse(candidate.trim());
  } catch {
    throw new CompanyError('planner returned invalid JSON', 400);
  }
  return MissionPlanSchema.parse(json); // ZodError → 400 via companyErrorInfo
}

/**
 * Create the plan's tasks under a mission. IDEMPOTENT: a task whose (normalized)
 * title already exists in the mission is skipped, so re-applying a plan never
 * duplicates. `dependsOn` references OTHER planned tasks by title; unknown/invalid
 * dependencies are skipped rather than failing the whole plan.
 */
export function applyMissionPlan(db: FounderDb, missionId: string, plan: MissionPlan): CompanyTask[] {
  if (!getMission(db, missionId)) throw new CompanyError('mission not found', 404);

  const titleToId = new Map<string, string>();
  for (const t of listTasksForMission(db, missionId)) titleToId.set(normTitle(t.title), t.id);

  const created: CompanyTask[] = [];
  for (const pt of plan.tasks) {
    const key = normTitle(pt.title);
    if (titleToId.has(key)) continue; // idempotent: already exists
    const task = createCompanyTask(db, missionId, {
      title: pt.title,
      objective: pt.objective,
      requiredCapabilities: pt.requiredCapabilities,
    });
    titleToId.set(key, task.id);
    created.push(task);
    appendEvent(db, { type: 'TASK_CREATED', missionId, taskId: task.id, summary: `Task created: ${task.title}` });
  }

  // Second pass: dependencies (by title). Invalid ones are skipped (never crash the plan).
  for (const pt of plan.tasks) {
    const taskId = titleToId.get(normTitle(pt.title));
    if (!taskId) continue;
    for (const depTitle of pt.dependsOn ?? []) {
      const depId = titleToId.get(normTitle(depTitle));
      if (!depId || depId === taskId) continue;
      try {
        addTaskDependency(db, taskId, depId);
      } catch {
        /* skip an invalid/cyclic dependency rather than failing the whole plan */
      }
    }
  }
  return created;
}

/** The LLM planner: mission → raw plan text. Grounded on the mission + the real capability catalog. */
async function defaultPlanner(db: FounderDb): Promise<(m: Mission) => Promise<string>> {
  const catalog = db.capabilities.all().map((c) => c.id);
  return async (mission: Mission) => {
    const system = [
      'You are the IGRIS Executive Manager. Decompose the mission into 2–6 concrete company tasks.',
      'Output ONLY a JSON object, no prose, matching:',
      '{"rationale":"...","tasks":[{"title":"...","objective":"...","requiredCapabilities":["domain.action"],"dependsOn":["Other task title"],"executionPreference":"agent|workflow|either"}]}',
      'Rules: requiredCapabilities MUST be lowercase domain.action ids; prefer these known capabilities when they fit:',
      catalog.length ? catalog.join(', ') : '(no capabilities defined yet — you may still propose ids)',
      'dependsOn references OTHER task titles in this plan. Keep it minimal and realistic.',
    ].join('\n');
    const res = await llmChat({ system, messages: [{ role: 'user', content: `Mission: ${mission.title}\nObjective: ${mission.objective ?? '(none)'}` }] });
    return res.text;
  };
}

/**
 * Plan a mission end to end: run the planner → validate → create tasks → activate
 * the mission (draft→active) → emit MISSION_PLANNED. No execution occurs here.
 */
export async function planMission(
  db: FounderDb,
  missionId: string,
  opts: { planner?: (m: Mission) => Promise<string> } = {},
): Promise<{ plan: MissionPlan; tasks: CompanyTask[] }> {
  const mission = getMission(db, missionId);
  if (!mission) throw new CompanyError('mission not found', 404);

  const planner = opts.planner ?? (await defaultPlanner(db));
  const raw = await planner(mission);
  const plan = parseMissionPlan(raw);
  const tasks = applyMissionPlan(db, missionId, plan);

  if (mission.status === 'draft') updateMission(db, missionId, { status: 'active' });
  appendEvent(db, { type: 'MISSION_PLANNED', missionId, summary: `Planned ${tasks.length} task(s)`, metadata: { taskCount: tasks.length } });
  return { plan, tasks };
}
